### ISSUE TITLE
Error deaggregating messages with Lambda

### ISSUE THREAD

**Issue by t-pascal** [awslabs/kinesis-deaggregation#2]
I am getting the following error. I appears that 'google' is not defined for the exception.

```
global name 'google' is not defined: NameError Traceback (most recent call last):
 File "/var/task/lambda-firehose.py", line 65, in lambda_handler
for record in deaggregate_records(event['Records']):
 File "/var/task/aws_kpl_deagg/deaggregator.py", line 108, in deaggregate_records
return_records.extend(iter_deaggregate_records(records))
 File "/var/task/aws_kpl_deagg/deaggregator.py", line 180, in iter_deaggregate_records
except google.protobuf.message.DecodeError as de:
 NameError: global name 'google' is not defined
```

Changing the code to...

```
except:
    is_aggregated = False
```

...bypasses the error.

**Comment by brentnash** [comment]
My apologies for the belated response.  Working on making the fix now.

Two quick thoughts:

1.  It seems like add `import google.protobuf.message` to the top of the file should fix the issue.

2.  If you're going to use the more generic `except:` workaround, may I suggest you use `except Exception as e:` instead?  I believe using raw `except` is frowned upon because it will also catch and handle things like VM shutdown and keyboard interrupts.

Thanks for the feedback!

**Comment by brentnash** [comment]
Fixed in this commit: https://github.com/awslabs/kinesis-deaggregation/commit/6031dc8821c2ee1c1ba1d76984163b1ad838ea62

**Comment by t-pascal** [comment]
Thanks for responding. I will test.

My exception example was merely to show that the exception line was causing the error and removing it from the code does not cause the error. I wanted to demonstrate that it wasn't something else.

I will probably be able to test by later next week.

**Comment by brentnash** [comment]
Makes sense.  Thanks!

**Comment by t-pascal** [comment]
I can confirm the fix works. However, we were hitting the exception for our kinesis data (which we then write to firehose). We are seeing binary data in our S3 buckets, so it seems that python deaggregation isn't working for us. If I have more data, I'll open an issue for it.

**Comment by brentnash** [comment]
Well that doesn't sound good.  If you happen to have any sample data or more details you can give me, I'd love to take a look.  Are you using the KPL to pack your data on the client side or are you packing them yourself?

Alternately, if you wanted to try a quick test, there is a KPL-based data generator app in the Java section of this repository (https://github.com/awslabs/kinesis-deaggregation/tree/master/java/KinesisTestProducers) that generates KPL-aggregated records and sends them to a Kinesis stream.  

Thanks again for all the feedback.  Feel free to open an issue like you mentioned if there's anything we can do on our end.

**Comment by t-pascal** [comment]
Thanks for the help. I have had a hard time debugging Lambda reading from Kinesis. We are currently writing records with the logstash Kinesis output (probably uses the Java client). Deaggregation works when we use the logstash Kinesis input module. However, our lambda clients have run into issues. I've tried the nodejs consumer from awslabs, and the java consumer from the awsblog. Both seem to have similar issues. So I'm not sure what is going on. When I have more information I'll open a new issue. Thanks.
