### ISSUE TITLE
JS deaggregation error due to reuse of hash

### ISSUE THREAD

**Issue by jeremywall** [awslabs/kinesis-deaggregation#3]
In the JS code there's an MD5 hash that's used during deaggregation. It's reused on line 70 here https://github.com/awslabs/kinesis-deaggregation/blob/master/node/node_modules/kpl-deagg/kpl-deagg.js#L70

But crypto objects are not reusable and when the update method is called the second time it fails with a "HashUpdate fail" error message.

It's a simple fix to just instantiate the md5 crypto object before each call to update. I submitted a pull request with the fix here https://github.com/awslabs/kinesis-deaggregation/pull/1

Can this fix be incorporated and rolled out to NPM?

**Comment by brentnash** [comment]
Thanks Jeremy!  I've merged in your pull request.  I'll work on getting NPM updated (I don't personally have the credentials to do so myself).

I'll leave this open until NPM is updated.

**Comment by jeremywall** [comment]
Fantastic, thank you. Whoever does keep the NPM credentials should also update the links to GitHub on the NPM page for this package. They incorrectly point to https://github.com/awslabs/kpl-deagg instead of https://github.com/awslabs/kinesis-deaggregation

**Comment by brentnash** [comment]
I'll add that to the list.  Thanks!

**Comment by brentnash** [comment]
We got the new version with this fix uploaded to NPM overnight:

https://www.npmjs.com/package/aws-kpl-deagg

I'm going to close this issue. 

Thanks again for the pull request and let us know if anything else comes up.
