### ISSUE TITLE
When no explicit has keys, deaggregation throws an IndexError

### ISSUE THREAD

**Issue by billletson** [awslabs/kinesis-deaggregation#5]
PR here: https://github.com/awslabs/kinesis-deaggregation/pull/4

If there are no explicit hash keys, attempting to index the ehks object fails with an IndexError:

list index out of range: IndexError Traceback (most recent call last): File "/var/task/function.py", line 38, in lambda_handler records = data_pipeline.extract_records_from_kinesis_event(lambda_event) File "/var/task/data_pipeline/utils.py", line 29, in extract_records_from_kinesis_event ret = [base64.b64decode(x['kinesis']['data']) for x in iter_deaggregate_records(event['Records'])] File "/var/task/aws_kpl_deagg/deaggregator.py", line 178, in iter_deaggregate_records error_string = _get_error_string(r, message_data, ehks, pks, ar) File "/var/task/aws_kpl_deagg/deaggregator.py", line 88, in _get_error_string (ehks[mr.explicit_hash_key_index] is not None, File "/var/task/google/protobuf/internal/containers.py", line 64, in __getitem__ return self._values[key] IndexError: list index out of range

**Comment by brentnash** [comment]
Thanks for the feedback.  Stuck in a class at the moment, but I'll attempt to get this patched in ASAP.

**Comment by brentnash** [comment]
Pull request has been merged.  I'm going to leave this issue open until I can submit the new version to Pypi.  Thanks!

**Comment by brentnash** [comment]
New version 1.0.10 is now available on PyPI:  https://pypi.python.org/pypi/aws_kpl_deagg

Closing issue.

Thanks Bill!
