### ISSUE TITLE
individual records ack - java

### ISSUE THREAD

**Issue by ngb18** [awslabs/kinesis-deaggregation#6]
Hi, 

What can be done to provide individual records acknowledgement in the java module, similar to what is provided in node.js ? What about checkpointing ? Thanks.

**Comment by brentnash** [comment]
Hi ngb18,

Could you give ussome more details on what you mean by "individual records acknowledgement" or point us to the piece of the NodeJS code that you're referring to?  Are you looking for a per-record callback?

As far as checkpointing goes, it depends on what methodology you're using to read from Kinesis.  Are you using Lambda?  Or the KCL?  Or are you doing it by hand?  I believe Lambda checkpoints for you and in the KCL case you're responsible for checkpointing yourself, though I've generally seen people checkpoint per batch rather than per record.

**Comment by ngb18** [comment]
Hi , 

Thanks for the response. Yes, i was looking for a Lambda checkpointing for a per-record basis.If there is an error in processing the Lambda for a kinesis stream record, the entire batch is sent back to be retried again. Is this understanding correct ?  What i would like is the ability to checkpoint the "processed" records, so that i do not have to process them again as an entire batch. Thanks for your help!

**Comment by brentnash** [comment]
Your understanding is mostly correct (see https://forums.aws.amazon.com/message.jspa?messageID=639825), but I did want to make one clarification:  the only way your Lambda function will "fail" (other than timing out) is if you have an uncaught exception or other fatal error.  If you wrap your per-record processing in a try/catch, you should be able to detect failing records (whatever failing means to you) and act on them appropriately.  That being said, I realize the streams API as we've provided it doesn't make that easy.

Would adding a new deaggregation method that takes in a single record solve your issue?  That way you could process your records one by one and easily use try/catch to detect the records that are malformed and handle them, but you'd be able to keep processing the entire batch.

As far as the checkpointing goes, I don't believe you can do your own checkpointing in Lambda.  I believe Lambda handles that for you.  It will checkpoint after each batch it processes.  You could in theory do what you want by setting a really small batch size, but I think that's a Kinesis/Lambda anti-pattern and I don't think I'd recommend it (though it obviously depends on how much data you're sending and how often).

**Comment by ngb18** [comment]
Thanks for the response. Where do i find more information on the Lambda checkpointing ? I have not come across any information for lambda checkpointing in aws docs.

**Comment by brentnash** [comment]
I'm not sure the docs explicitly call out the checkpointing behavior anywhere.  Let me follow up with the team and see what the official stance is.  The closest I can find is from the FAQ (https://aws.amazon.com/lambda/faqs/) where it explains failure behavior:

```
Q: What happens if my function fails while processing an event?

For Amazon S3 bucket notifications and custom events, AWS Lambda will attempt execution of your function three times in the event of an error condition in your code or if you exceed a service or resource limit. For ordered event sources that AWS Lambda polls on your behalf, such as Amazon DynamoDB Streams and Amazon Kinesis streams, Lambda will continue attempting execution in the event of a developer code error until the data expires. You can monitor progress through the Amazon Kinesis and Amazon DynamoDB consoles and through the Amazon CloudWatch metrics that AWS Lambda generates for your function. You can also set Amazon CloudWatch alarms based on error or execution throttling rates.
```

I've got an update in the works that will provide an API to let you deaggregate on a per-record basis as well.  It will hopefully be ready in the next week or two.

**Comment by ngb18** [comment]
Hi, Thanks for the response! I wanted to follow up to see if you have an official stance from the team about the checkpointing. Appreciate your time!.

**Comment by brentnash** [comment]
I'm sorry, I was out of the office for a few days.  I pinged the team again.  I'll let you know what I find out.

**Comment by brentnash** [comment]
OK, I just confirmed with the team.  Lambda does indeed handle checkpointing on your behalf.  It will checkpoint after a successfully processed batch of records.  There is currently no way to checkpoint a partial batch (i.e. you can't checkpoint partway through processing a batch).  If you want to checkpoint more frequently, your best option at the moment is to reduce your batch size (smaller batches = more frequent checkpoints).

I believe that definitively answers your questions, so I'm going to go ahead and close this issue.  If you have further questions, feel free to reopen the issue or create a new one.
